---
- name: Create Arista Vlans
  hosts: arista
  gather_facts: false

  tasks:
    - name: create Server Vlan
      eos_vlan: name=SERVER vlanid=101
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: create Storage Vlan
      eos_vlan: name=STORAGE vlanid=102
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: create vMotion Vlan
      eos_vlan: name=vMOTION vlanid=103
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https


- name: Configure Ethernet5 Interface Description
  hosts: arista
  gather_facts: false

  tasks:
    - name: Task to configure Eth5 descirption
      eos_interface: name=Ethernet5 description="** CdL Test **" 
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
            

- name: Configure Ethernet5 as trunk with allowed vlans 
  hosts: arista
  gather_facts: false

  tasks:

    - name: Task to configure Eth5 access parameters
      eos_switchport: name={{ item }} mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=101,102,103 
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - Ethernet5


- name: Arista Default Interface (Manual)
  hosts: arista
  gather_facts: false

  tasks:

    - name: Task to remove description
      eos_interface: name={{ item }} description=""
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - Ethernet5
      tags:
            - cleanup


    - name: Task to remove interface configuration
      eos_switchport: name={{ item }} mode=access access_vlan=1 trunk_native_vlan=1 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - Ethernet5

      tags:
            - cleanup


    - name: Remove Created Vlans
      eos_vlan: name={{ item.name }} vlanid={{ item.num }} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - {name: SERVER, num: 101}
            - {name: STORAGE , num: 102}
            - {name: vMOTION, num: 103}

      tags:
            - cleanup



