---

- name: Cisco IOS File Transfer Test
  hosts: cisco
  gather_facts: false

  tasks:
  - name: Task Testing File Transfer
    cisco_file_transfer:
         source_file="/home/cdeluna/scratch/week6/cisco_acl.txt"
         dest_file=cisco_acl.txt
         overwrite=true
         enable_scp=true
         host={{ host }}
         port={{ port }}
         username={{ username }}
         password={{ password }}
    register: output

  - debug: var=output

      

