---
# tasks file for access_switch
- name: Configurations
  template: src=access_switch3.j2 dest=/home/cdeluna/scratch/week5/GEN_CONFIGS/{{item.hostname}}.txt
  register: vars
  with_items: sw_list

- name: Task to Print Variables
  debug: var=vars
